	var quiz = {"qref":"qt24fe97bb4d857c","quiztitle":"LDC 1 SAQs","quizdescription":"LDC: 1: Recognition of Normal Labour: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:00","q":[{"refid":"qqt24fe97bb52f8ee","orderno":"1","text":"Lightening is when the baby floats higher in the abdomen shortly before labour begins.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb576bcc","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false. Lightening is when the baby drops lower in the abdomen before labour begins."}},{"refid":"qqrt24fe97bb58c807","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false. Lightening is when the baby drops lower in the abdomen before labour begins."}}]},{"refid":"qqt24fe97bb5ab1a1","orderno":"2","text":"The second stage of labour ends with the expulsion of the baby from the birth canal.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb5b7582","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. The second stage of labour ends with the expulsion of the baby from the birth canal."}},{"refid":"qqrt24fe97bb5c9b3c","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. The second stage of labour ends with the expulsion of the baby from the birth canal."}}]},{"refid":"qqt24fe97bb5e84ff","orderno":"3","text":"The fourth stage of labour lasts for 4 hours and begins when the placenta and fetal membranes have been expelled.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb6006a0","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. The fourth stage of labour lasts for 4 hours and begins when the placenta and fetal membranes have been expelled."}},{"refid":"qqrt24fe97bb6116d9","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. The fourth stage of labour lasts for 4 hours and begins when the placenta and fetal membranes have been expelled."}}]}]};
	if (!mQ.quizInCache('qt24fe97bb4d857c')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bb6a541d","quiztitle":"LDC 2 SAQs","quizdescription":"LDC: 2: Assessing the Woman in Labour: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:02","q":[{"refid":"qqt24fe97bb6b8188","orderno":"1","text":"A temperature of 39\u00b0C indicates a high grade fever.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb6c44bc","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. A high grade fever is a temperature above 38.5\u00baC (low grade fever is between 37.5-38.4\u00baC."}},{"refid":"qqrt24fe97bb6d6ac2","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. A high grade fever is a temperature above 38.5\u00baC (low grade fever is between 37.5-38.4\u00baC."}}]},{"refid":"qqt24fe97bb70535b","orderno":"2","text":"The gestational age is how old the mother is when she becomes pregnant.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb711724","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false. The gestational age is the number of weeks the fetus has been in the uteral calculated from the date when the women\u2019s last normal menstrual period (LNMP) began."}},{"refid":"qqrt24fe97bb72ca13","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false. The gestational age is the number of weeks the fetus has been in the uteral calculated from the date when the women\u2019s last normal menstrual period (LNMP) began."}}]},{"refid":"qqt24fe97bb757758","orderno":"3","text":"Parity is the number of babies delivered alive after 28 weeks of gestation.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb782385","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false. Parity is the number of babies delivered either alive or dead after 28 weeks of gestation."}},{"refid":"qqrt24fe97bb7969b2","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false. Parity is the number of babies delivered either alive or dead after 28 weeks of gestation."}}]}]};
	if (!mQ.quizInCache('qt24fe97bb6a541d')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bb8652d6","quiztitle":"LDC 3 SAQs","quizdescription":"LDC: 3: Care of the Woman in Labour: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:04","q":[{"refid":"qqt24fe97bb881fc0","orderno":"1","text":"Maternal preference means respecting how the mother wants to give birth.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb88e339","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. Respecting maternal preferences includes how she wants to give birth."}},{"refid":"qqrt24fe97bb8a49f7","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. Respecting maternal preferences includes how she wants to give birth."}}]},{"refid":"qqt24fe97bb8c5491","orderno":"2","text":"In the first stage of labour the mother should not drink anything in case she vomits.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb8d1856","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false. During the first stage of labour the mother should drink at least one cup of fluid every hour to prevent dehydration."}},{"refid":"qqrt24fe97bb8e61d5","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false. During the first stage of labour the mother should drink at least one cup of fluid every hour to prevent dehydration."}}]},{"refid":"qqt24fe97bb950578","orderno":"3","text":"The frequency of contractions refers to how painful the contractions become.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bb95c8fd","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false. The frequency of contractions refers to how often they come in every 10 minute period during the labour; it does not refer to how painful they become, which is the strength of contractions."}},{"refid":"qqrt24fe97bb976636","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false. The frequency of contractions refers to how often they come in every 10 minute period during the labour; it does not refer to how painful they become, which is the strength of contractions."}}]}]};
	if (!mQ.quizInCache('qt24fe97bb8652d6')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bba26bd3","quiztitle":"LDC 4 SAQs","quizdescription":"LDC: 4: Using the Partograph: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:06","q":[{"refid":"qqt24fe97bba39aad","orderno":"1","text":"Give two reasons for using a partograph.","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bba521e9","orderno":"2","text":"What indicators of good progress of labour would you record on the partograph?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bba6da39","orderno":"3","text":"How often should you measure the vital signs of the mother and record them on the partograph in a normally progressing labour?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]}]};
	if (!mQ.quizInCache('qt24fe97bba26bd3')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bbb02cea","quiztitle":"LDC 5 SAQs","quizdescription":"LDC: 5: Conducting a Normal Delivery: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:07","q":[{"refid":"qqt24fe97bbb15a82","orderno":"1","text":"Full dilatation of the cervix to 10 cm is the most important sign that the second stage of labour is beginning.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bbb21e61","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. Full dilatation of the cervix to 10 cm is the most important sign that second stage of labour is beginning."}},{"refid":"qqrt24fe97bbb343dd","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. Full dilatation of the cervix to 10 cm is the most important sign that second stage of labour is beginning."}}]},{"refid":"qqt24fe97bbb55970","orderno":"2","text":"In second stage, the mother\u2019s genitals tend to bulge during contractions and relax between contractions.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bbb61d71","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. In second stage, the mother\u2019s genitals tend to bulge during contractions and relax between contractions."}},{"refid":"qqrt24fe97bbb74300","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. In second stage, the mother\u2019s genitals tend to bulge during contractions and relax between contractions."}}]},{"refid":"qqt24fe97bbb94273","orderno":"3","text":"Crowning is the name given to the moment when the baby\u2019s head is completely born.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bbba0652","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false. Crowning is when the top of the baby\u2019s head stretches the vaginal opening to the size of your hand and it stays in the opening even between contractions."}},{"refid":"qqrt24fe97bbbb2c07","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false. Crowning is when the top of the baby\u2019s head stretches the vaginal opening to the size of your hand and it stays in the opening even between contractions."}}]}]};
	if (!mQ.quizInCache('qt24fe97bbb02cea')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bbc567de","quiztitle":"LDC 6 SAQs","quizdescription":"LDC: 6: Active Management of the Third Stage of Labour: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:08","q":[{"refid":"qqt24fe97bbc84534","orderno":"1","text":"How do you define the third stage of labour?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bbc9ccb8","orderno":"2","text":"What physiological changes happen during the third stage of a normal uncomplicated labour?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bbcbc174","orderno":"3","text":"Imagine that you have managed the third stage of labour for a woman in your community by correctly using AMTSL, but she has developed continuous bleeding. Do you provide additional misoprostol? If yes, what dose should you give her and in what form?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]}]};
	if (!mQ.quizInCache('qt24fe97bbc567de')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bbd74a62","quiztitle":"LDC 7 SAQs","quizdescription":"LDC: 7: Neonatal Resuscitation: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:09","q":[{"refid":"qqt24fe97bbd87b31","orderno":"1","text":"If a newborn cries soon after birth, it is a sign of asphyxia occurring before delivery.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bbd9f6da","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false."}},{"refid":"qqrt24fe97bbdb4866","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false."}}]},{"refid":"qqt24fe97bbdd93e2","orderno":"2","text":"Cyanosis means being covered with meconium all over the body.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bbde57cc","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false. Cyanosis means having a bluish colour to the skin because of oxygen shortage (asphyxia)."}},{"refid":"qqrt24fe97bbe27c00","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false. Cyanosis means having a bluish colour to the skin because of oxygen shortage (asphyxia)."}}]},{"refid":"qqt24fe97bbe69dcd","orderno":"3","text":"The apical heartbeat can be detected by listening to the baby\u2019s chest with a stethoscope.","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bbe79751","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. The apical heartbeat can be detected by listening to the baby\u2019s chest with a stethoscope."}},{"refid":"qqrt24fe97bbe8bd59","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. The apical heartbeat can be detected by listening to the baby\u2019s chest with a stethoscope."}}]}]};
	if (!mQ.quizInCache('qt24fe97bbd74a62')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bbf320f4","quiztitle":"LDC 8 SAQs","quizdescription":"LDC: 8: Abnormal Presentations and Multiple Pregnancies: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:11","q":[{"refid":"qqt24fe97bbf44e5a","orderno":"1","text":"Fundus \u2014 the \u2018rounded top\u2019 and widest cavity of the uterus. Is this definition:","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bbf5738f","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. The fundus is the \u2018rounded top\u2019 and widest cavity of the uterus."}},{"refid":"qqrt24fe97bbf69924","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. The fundus is the \u2018rounded top\u2019 and widest cavity of the uterus."}}]},{"refid":"qqt24fe97bc004cfa","orderno":"2","text":"Complete breech \u2014 where the legs are bent at both hips and knee joints and are folded underneath the baby. Is this definition:","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bc041745","orderno":"1","text":"true","score":"10","props":{"feedback":"Correct! It is true. Complete breech is where the legs are bent at both hips and knee joints and are folded underneath the baby."}},{"refid":"qqrt24fe97bc05db26","orderno":"2","text":"false","score":"0","props":{"feedback":"It is true. Complete breech is where the legs are bent at both hips and knee joints and are folded underneath the baby."}}]},{"refid":"qqt24fe97bc09cdaf","orderno":"3","text":"Frank breech \u2014 where the breech is so difficult to treat that you have to be very frank and open with the mother about the difficulties she will face in the birth. Is this definition:","type":"multichoice","props":{"maxscore":"10","type":"multichoice"},"r":[{"refid":"qqrt24fe97bc0b1ef7","orderno":"1","text":"true","score":"0","props":{"feedback":"It is false. A frank breech is the most common type of breech presentation and is when the baby\u2019s legs point straight upwards"}},{"refid":"qqrt24fe97bc0cbbb5","orderno":"2","text":"false","score":"10","props":{"feedback":"Correct! It is false. A frank breech is the most common type of breech presentation and is when the baby\u2019s legs point straight upwards"}}]}]};
	if (!mQ.quizInCache('qt24fe97bbf320f4')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bc179ffe","quiztitle":"LDC 9 SAQs","quizdescription":"LDC: 9: Obstructed Labour: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:13","q":[{"refid":"qqt24fe97bc18fa77","orderno":"1","text":"What do you understand by the term 'Perinatal mortality and morbidity'?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bc1bbc03","orderno":"2","text":"What do you understand by the term 'Prolonged latent phase of labour'?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bc1d6fbe","orderno":"3","text":"What do you understand by the term 'Prolonged second stage of labour'?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]}]};
	if (!mQ.quizInCache('qt24fe97bc179ffe')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bc27a65f","quiztitle":"LDC 10 SAQs","quizdescription":"LDC: 10: Ruptured Uterus: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:14","q":[{"refid":"qqt24fe97bc29008f","orderno":"1","text":"What are the main factors that may predispose a woman to develop a uterine rupture?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bc2a8813","orderno":"2","text":"Why are multiparous women at greater risk of uterine rupture than primiparous women?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bc2cd37b","orderno":"3","text":"What complications may follow uterine rupture?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]}]};
	if (!mQ.quizInCache('qt24fe97bc27a65f')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
	var quiz = {"qref":"qt24fe97bc372380","quiztitle":"LDC 11 SAQs","quizdescription":"LDC: 11: Postpartum Haemorrhage: SAQs","maxscore":"30","lastupdate":"2012-06-26 10:07:15","q":[{"refid":"qqt24fe97bc3847f8","orderno":"1","text":"You are assessing a pregnant woman in your care for potential risk of PPH. What questions would you ask her and what would you remember to check as part of your antenatal care visit?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bc39c40e","orderno":"2","text":"You are assessing a pregnant woman in your care for potential risk of PPH. What checks and interventions would you make during her labour and delivery?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]},{"refid":"qqt24fe97bc3b6c6a","orderno":"3","text":"Gelila delivered a baby 40 minutes ago. You gave her 600 \u00b5g of misoprostol orally immediately after the birth, but the placenta has not come out yet. She has emptied her bladder. After 10 minutes the placenta comes out and you check that it is intact, but Gelila starts bleeding heavily. What do you do?","type":"essay","props":{"maxscore":"10","type":"essay"},"r":[]}]};
	if (!mQ.quizInCache('qt24fe97bc372380')) {
		mQ.store.addArrayItem('quizzes', quiz);
	}
